config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  post  '/signup',  to: 'users#create'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/apply', to: 'applicants#apply', as: 'apply'
  resources :users
  resources :employers
  resources :applicants
end

app/models/applicant.rb
class Applicant < User
  has_many :mappings
  has_many :employers, through: :mappings
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update, :destroy]

  # GET /applicants
  # GET /applicants.json
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
    @applicant = Applicant.find(params[:id])
  end

  # GET /applicants/apply
  def apply
    @employer = Employer.find(params[:employer_id])
    msg = ""
    unless current_user.employers.include? @employer
      current_user.employers << @employer
      msg = "You successfully applied to #{@employer.name}!"
    else
      msg = "You have already applied to #{@employer.name}!"
    end
    flash[:success] = msg
    redirect_back_or current_user
  end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to @applicant, notice: 'Applicant was successfully created.' }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1
  # PATCH/PUT /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1
  # DELETE /applicants/1.json
  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to applicants_url, notice: 'Applicant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_params
      params.require(:applicant).permit(:type, :name, :email, :password, :password_confirmation)
    end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/applicants/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :type , "Select User Type"%>
  <%= f.select :type, [ 'Employer', 'Applicant' ], default: 'Employer'%>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing Applicant</h1>

<%= render 'form', applicant: @applicant %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
<p id="notice"><%= notice %></p>

<h1> All Applicants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applicants.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Applicant', new_user_path %>

app/views/applicants/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <h2>Already a user? <%= link_to "Login here!", login_path %></h2>
  </div>
</div>

app/views/applicants/show.html.erb
<% provide(:title, @applicant.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <p>
        <h1>User Type: <%= @applicant.type %></h1>
      </p>

      <p>
        <h1>Name: <%= @applicant.name %></h1>
      </p>

      <p>
        <h1>Email: <%= @applicant.email %></h1>
      </p>
      <p>
        <%= link_to 'Edit', edit_applicant_path(@applicant) %> |
        <%= link_to 'Back', applicants_path %>
      </p>
    </section>
  </aside>
</div>

<table>
  <caption><h3>Employers</h3></caption>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Application status</th>
    </tr>
  </thead>

  <tbody>
    <% Employer.all.each do |employer| %>
      <tr>
        <td><%= employer.name %></td>
        <td><%= employer.email %></td>
        <% unless current_user.employers.include? employer %>
          <td><%= button_to 'Apply', apply_path(:employer_id => employer.id) %></td>
        <% else %>
          <td>Already applied!</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>