config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  post  '/signup',  to: 'users#create'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/apply', to: 'applicants#apply', as: 'apply'
  resources :users
  resources :employers
  resources :applicants
end

app/models/employer.rb
class Employer < User
  has_many :mappings
  has_many :applicants, through: :mappings
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  before_action :set_employer, only: [:show, :edit, :update, :destroy]

  # GET /employers
  # GET /employers.json
  def index
    @employers = Employer.all
  end

  # GET /employers/1
  # GET /employers/1.json
  def show
  end

  # GET /employers/new
  def new
    @employer = Employer.new
  end

  # GET /employers/1/edit
  def edit
    @employer = Employer.find(params[:id])
  end

  # POST /employers
  # POST /employers.json
  def create
    @user = Employer.new(employer_params)

    if @user.save
      login_url @user
      flash[:success] = "Welcome to the Jobs App!"
      redirect_to login_url
    else
      render 'new'
    end
  end

  # PATCH/PUT /employers/1
  # PATCH/PUT /employers/1.json
  def update
    respond_to do |format|
      if @employer.update(employer_params)
        format.html { redirect_to @employer, notice: 'Employer was successfully updated.' }
        format.json { render :show, status: :ok, location: @employer }
      else
        format.html { render :edit }
        format.json { render json: @employer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employers/1
  # DELETE /employers/1.json
  def destroy
    @employer.destroy
    respond_to do |format|
      format.html { redirect_to employers_url, notice: 'Employer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employer
      @employer = Employer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employer_params
      params.require(:employer).permit(:type, :name, :email, :password, :password_confirmation)
    end
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/views/employers/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :type , "Select User Type"%>
  <%= f.select :type, [ 'Employer', 'Applicant' ], default: 'Employer'%>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/employers/edit.html.erb
<h1>Editing Employer</h1>

<%= render 'form', employer: @employer %>

<%= link_to 'Show', @employer %> |
<%= link_to 'Back', employers_path %>

app/views/employers/index.html.erb
<p id="notice"><%= notice %></p>

<h1> All Employers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employers.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employer', new_user_path %>

app/views/employers/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <h2>Already a user? <%= link_to "Login here!", login_path %></h2>
  </div>
</div>

app/views/employers/show.html.erb
<% provide(:title, @employer.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <p>
        <h1>User Type: <%= @employer.type %></h1>
      </p>

      <p>
        <h1>Name: <%= @employer.name %></h1>
      </p>

      <p>
        <h1>Email: <%= @employer.email %></h1>
      </p>
      <p>
        <%= link_to 'Edit', edit_employer_path(@employer) %> |
        <%= link_to 'Back', employers_path %>
      </p>
    </section>
  </aside>
</div>

<table style="width:50%">
  <caption>Your Applicants</caption>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @employer.applicants.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>